<a href="https://colab.research.google.com/github/windopper/NerualNetworkPracticeInJupyter/blob/main/textpreprocessing/splitting_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

#x와 y분리하기
zip 함수를 이용하여 분리하기

In [3]:
x, y = zip(['a', 1], ['b', 2], ['c', 3])
print('x 데이터 :', x)
print('y 데이터 :', y)

x 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [9]:
sequences = [['a', 1], ['b', 2], ['c', 3]]
x, y = zip(*sequences)
print('x 데이터 :', x)
print('y epdlxj :', y)

x 데이터 : ('a', 'b', 'c')
y epdlxj : (1, 2, 3)


데이터프레임을 이용하여 분리하기

In [12]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

데이터 프레임은 열의 이름으로 각 열에 접근이 가능하므로, 이를 이용하여 손쉽게 X데이터와 Y데이터를 분리할 수 있음

In [22]:
x = df['메일 본문']
y = df['스팸 메일 유무']

print('x 데이터 :', x.to_list())
print('y 데이터 :', y.to_list())

x 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


Numpy를 이용하여 분리하기

In [17]:
np_array = np.arange(0, 16).reshape(4, 4)
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [18]:
x = np_array[:, :3]
y = np_array[:, 3]

print('x 데이터 :')
print(x)
print('y 데이터 :', y)

x 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


# 테스트 데이터 분리하기

사이킷 런을 이용하여 분리하기

사이킷 런은 학습용 데이터와 테스트용 데이터를 쉽게 분리할 수 있게 해주는 train_test_split()를 지원합니다

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1234)

x: 독립 변수 데이터

y: 종속 변수 데이터

test_size: 데스트용 데이터 개수 지정. 1보다 작은 실수 기재시 비율을 나타냄

train_size: 학습용 데이터의 개수를 지정. 1보다 작은 실수 기재시 비율을 나타냄

random_state: 난수시드

In [25]:
x, y = np.arange(10).reshape((5, 2)), range(5)

print('x 전체 데이터 :')
print(x)
print('y 전체 데이터 :')
print(list(y))

x 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0, 1, 2, 3, 4]


In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1234)

print('x 훈련 데이터 :')
print(x_train)
print('x 테스트 데이터 :')
print(x_test)

x 훈련 데이터 :
[[2 3]
 [4 5]
 [6 7]]
x 테스트 데이터 :
[[8 9]
 [0 1]]


70%의 비율로 분리된 x의 훈련 데이터와 30%의 비율로 분리된 y의 테스트 데이터

In [30]:
print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

y 훈련 데이터 :
[1, 2, 3]
y 테스트 데이터 :
[4, 0]
